version: '3.9'
services:

  # Nats
  nats:
    image: nats:2.7.4
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
  
  # Organization dashboard    
  organization-dashboard:
    image: ghcr.io/fontys-stress-wearables/organisation-dashboard:main
    depends_on:
      user-service:
        condition: service_started
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "3030:80"

  # Caregiver dashboard    
  caregiver-dashboard:
    image: ghcr.io/fontys-stress-wearables/caregiver-dashboard:main
    depends_on:
      user-service:
        condition: service_started
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "3000:80"

  # Stress Data Service
  stress-data-service:
    image: ghcr.io/fontys-stress-wearables/stress-data-service:main
    ports:
      - "5031:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    depends_on:
      - nats
      - stress-data-influxdb

  # InfluxDb of Stress Data Service
  stress-data-influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=rbAKz20QR4u5J8
      - DOCKER_INFLUXDB_INIT_ORG=SWSP
      - DOCKER_INFLUXDB_INIT_BUCKET=StressData
        
  # Stress Algorithm Service
  stress-algorithm-service:
    image: ghcr.io/fontys-stress-wearables/stress-algorithm-service:master
    ports:
      - "5032:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging

  # Feedback Service
  feedback-service:
    container_name: feedback-service
    image: ghcr.io/fontys-stress-wearables/feedback-service:main
    ports:
      - "5005:80"
    networks:
      - default
    environment:
      ASPNETCORE_ENVIRONMENT: Staging

  feedback-db:
    container_name: feedback-db
    image: mongo
    networks:
      - default
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

  # User service
  user-postgres:
    image: postgres:14.2
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
      POSTGRES_DB: "userservice"

  user-service:
    container_name: user-service
    image: ghcr.io/fontys-stress-wearables/user-service:main
    depends_on:
      - user-postgres
    ports:
      - "5054:80"
    networks:
      - default
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      AzureAd__ClientSecret: ${AZURE_CLIENT_SECRET}
      AzureAd__GraphScope: ${AZURE_GRAPH_SCOPE}
      AzureAd__ClientId: ${AZURE_CLIENT_ID}

# join swsp
networks:
  default:
    name: swsp

# Define storage location
volumes:
  mongodbdata: